name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [arm, arm64]
    runs-on: ubuntu-22.04
    env:
      CMAKE_VERSION: 3.18.4

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.6'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y --fix-missing build-essential gcc-multilib python3 unzip pkg-config p7zip-full
        cd /home/runner/
        wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz
        tar xvf cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz

    - name: Build native libraries
      run: |
        export PATH=/home/runner/cmake-$CMAKE_VERSION-Linux-x86_64/bin/:$PATH
        cd buildscripts
        ./build.sh --arch ${{ matrix.arch }}

    - name: Update Gradle Configuration
      run: |
        echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
        echo "kotlin.code.style=official" >> gradle.properties
        
        # Обновляем build.gradle
        cat << EOF >> build.gradle
        buildscript {
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
                maven { url "https://jitpack.io" }
            }
        }
        EOF
        
        # Обновляем settings.gradle
        cat << EOF > settings.gradle
        dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
            repositories {
                google()
                mavenCentral()
                maven { url "https://jitpack.io" }
            }
        }
        rootProject.name = 'OMW-ONLINE'
        include ':app'
        EOF

    - name: Build the APK
      run: |
        ARCH=${{ matrix.arch }}
        source buildscripts/include/version.sh
        sed -i "s/abiFilters.*/abiFilters '$ABI'/" app/build.gradle
        export ANDROID_NDK_HOME=$(pwd)/buildscripts/toolchain/ndk/
        chmod +x gradlew
        ./gradlew wrapper --gradle-version 7.6
        ./gradlew clean
        ./gradlew assembleNightlyDebug --stacktrace --info

    - name: Collect outputs
      id: getfilename
      run: |
        mv app/build/outputs/apk/nightly/debug/omw_debug_*.apk omw-debug-$(git rev-parse --short "$GITHUB_SHA")-${{ matrix.arch }}.apk
        echo "apk_file=$(ls omw-debug-*.apk | sed 's/\(.*\)\..*/\1/')" >> $GITHUB_OUTPUT

    - name: Upload the APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.getfilename.outputs.apk_file }}
        path: ${{ steps.getfilename.outputs.apk_file }}.apk
